apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-chart.fullname" . }}-init-script
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
data:
  init-mongo.sh: |
    #!/bin/bash
    set -e # Lo script si interrompe se un comando fallisce

    echo "--- INIZIO IMPORTAZIONE DATI INIZIALI IN MONGODB ---"
    
    # Esegue il comando di importazione usando i valori da values.yaml
    mongoimport \
      --db {{ .Values.database.name }} \
      --collection {{ .Values.database.collection }} \
      --file /data/init/{{ .Values.database.initDataFileName }} \
      --jsonArray
      
    echo "--- IMPORTAZIONE COMPLETATA ---"