# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongodb-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mongodb-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongo-init-script-volume
              mountPath: /docker-entrypoint-initdb.d/
            - name: mongo-init-data-volume
              mountPath: /data/init/
      volumes:
        - name: mongo-init-script-volume
          configMap:
            name: {{ include "mongodb-chart.fullname" . }}-init-script
            defaultMode: 0755
        - name: mongo-init-data-volume
          configMap:
            name: {{ include "mongodb-chart.fullname" . }}-init-data