apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "mongodb-chart.selectorLabels" . | nindent 4 }}