apiVersion: v1
kind: Namespace
metadata:
 name: aimusei

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: aimusei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: be
          image: harbor-adarte-coll.museiitaliani.it/adarte/aimusei_be:1.0
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo-service:27017/aimusei?connectTimeoutMS=30000&socketTimeoutMS=30000"
          command:
            - "java"
            - "-jar"
            - "app.jar"
            - "--spring.config.location=file:/app/config/config.properties"
            - "--server.port=8090"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: datasources-volume
              mountPath: /opt/ai/config
      volumes:
        - name: config-volume
          configMap:
            name: backend-config
        - name: datasources-volume
          configMap:
            name: datasources-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: aimusei
data:
  config.properties: |
    server.servlet.context-path=/api  
    spring.data.mongodb.uri=mongodb://mongo-service:27017/aimusei
    aimusei.key=keytest123123
    logging.level.org.springframework.data.mongodb=DEBUG
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources-config
  namespace: aimusei
data:
  datasources.env: |
    mongo.host=mongo-service
    mongo.database=aimusei
    spring.data.mongodb.uri=mongodb:///mongo-service:27017/
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: aimusei
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8090
      targetPort: 8090
