apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameBase }}-fe-service
  labels:
    app: {{ .Values.nameBase }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "frontend-chart.selectorLabels" . | nindent 4 }}