apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameBase }}-be-service
  labels:
    app: {{ .Values.nameBase }}-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.nameBase }}-backend